// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-ZRX7MYPdzBmo38ksZOT8Y5SDvn3mbGg',
    appId: '1:569173351536:web:d33f4d53c188c6e89368b5',
    messagingSenderId: '569173351536',
    projectId: 'connect-8d1ed',
    authDomain: 'connect-8d1ed.firebaseapp.com',
    storageBucket: 'connect-8d1ed.firebasestorage.app',
    measurementId: 'G-2561BH3SKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmryhH_HwV-zpxFPVl_0HFVkcHUbhhzq4',
    appId: '1:569173351536:android:60f6213985922c869368b5',
    messagingSenderId: '569173351536',
    projectId: 'connect-8d1ed',
    storageBucket: 'connect-8d1ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDZE3u_K_LHNu3uNxQ_K2Luu7Z0p2XPBI',
    appId: '1:569173351536:ios:d2d062ddd31666cf9368b5',
    messagingSenderId: '569173351536',
    projectId: 'connect-8d1ed',
    storageBucket: 'connect-8d1ed.firebasestorage.app',
    iosBundleId: 'com.example.testeFlutter',
  );
}
